// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package types

type FetchContactsListReq struct {
	AppId                    string `json:"appId"`
	XGEWETOKEN               string `header:"X-GEWE-TOKEN"`
	AuthorizContentTypeation string `header:"Content-Type"`
}

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Message string `json:"message"`
}
