// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGroup = "group"

// Group mapped from table <group>
type Group struct {
	ID          string    `gorm:"column:id;primaryKey" json:"id"`
	Username    string    `gorm:"column:username;not null" json:"username"`
	Nickname    string    `gorm:"column:nickname;not null" json:"nickname"`
	DisplayName string    `gorm:"column:display_name;not null" json:"display_name"`
	CreatedAt   time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName Group's table name
func (*Group) TableName() string {
	return TableNameGroup
}
