// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package handler

import (
	"net/http"

	"bot/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/from/:name",
				Handler: BotHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CallbackMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/callback",
					Handler: CallbackHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/v1"),
	)
}
