// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package handler

import (
	"net/http"

	logic "bot/internal/handler/logic"
	normal "bot/internal/handler/normal"
	"bot/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/from/:name",
				Handler: BotHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/fetchContactsList",
				Handler: logic.FetchContactsListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CallbackMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/callback",
					Handler: normal.CallbackHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/contacts/fetchContactsList",
					Handler: normal.SyncHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/v1"),
	)
}
