// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameChatroom = "chatroom"

// Chatroom mapped from table <chatroom>
type Chatroom struct {
	ID              int32  `gorm:"column:id;primaryKey" json:"id"`
	ChatroomID      string `gorm:"column:chatroom_id" json:"chatroom_id"`
	NickName        string `gorm:"column:nick_name" json:"nick_name"`
	PyInitial       string `gorm:"column:py_initial" json:"py_initial"`
	QuanPin         string `gorm:"column:quan_pin" json:"quan_pin"`
	Sex             int32  `gorm:"column:sex" json:"sex"`
	Remark          string `gorm:"column:remark" json:"remark"`
	RemarkPyInitial string `gorm:"column:remark_py_initial" json:"remark_py_initial"`
	RemarkQuanPin   string `gorm:"column:remark_quan_pin" json:"remark_quan_pin"`
	ChatRoomNotify  int32  `gorm:"column:chat_room_notify" json:"chat_room_notify"`
	ChatRoomOwner   string `gorm:"column:chat_room_owner" json:"chat_room_owner"`
	SmallHeadImgURL string `gorm:"column:small_head_img_url" json:"small_head_img_url"`
}

// TableName Chatroom's table name
func (*Chatroom) TableName() string {
	return TableNameChatroom
}
