// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMember = "member"

// Member mapped from table <member>
type Member struct {
	ID              int32  `gorm:"column:id;primaryKey" json:"id"`
	Wxid            string `gorm:"column:wxid" json:"wxid"`
	NickName        string `gorm:"column:nick_name;not null" json:"nick_name"`
	InviterUserName string `gorm:"column:inviter_user_name" json:"inviter_user_name"`
	MemberFlag      int32  `gorm:"column:member_flag;not null" json:"member_flag"`
	DisplayName     string `gorm:"column:display_name" json:"display_name"`
	BigHeadImgURL   string `gorm:"column:big_head_img_url" json:"big_head_img_url"`
	SmallHeadImgURL string `gorm:"column:small_head_img_url" json:"small_head_img_url"`
	ChatroomID      string `gorm:"column:chatroom_id" json:"chatroom_id"`
	IsOwner         bool   `gorm:"column:is_owner;not null" json:"is_owner"`
	IsAdmin         bool   `gorm:"column:is_admin;not null" json:"is_admin"`
}

// TableName Member's table name
func (*Member) TableName() string {
	return TableNameMember
}
