// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMsg = "msg"

// Msg mapped from table <msg>
type Msg struct {
	ID           int32  `gorm:"column:id;primaryKey" json:"id"`
	MsgID        int32  `gorm:"column:MsgId" json:"MsgId"`
	FromUserName string `gorm:"column:FromUserName" json:"FromUserName"`
	ToUserName   string `gorm:"column:ToUserName" json:"ToUserName"`
	MsgType      int32  `gorm:"column:MsgType" json:"MsgType"`
	Content      string `gorm:"column:Content" json:"Content"`
	Status       int32  `gorm:"column:Status" json:"Status"`
	ImgStatus    int32  `gorm:"column:ImgStatus" json:"ImgStatus"`
	ImgBufILen   int32  `gorm:"column:ImgBuf_iLen" json:"ImgBuf_iLen"`
	CreateTime   int32  `gorm:"column:CreateTime" json:"CreateTime"`
	MsgSource    string `gorm:"column:MsgSource" json:"MsgSource"`
	PushContent  string `gorm:"column:PushContent" json:"PushContent"`
	NewMsgID     int32  `gorm:"column:NewMsgId" json:"NewMsgId"`
	MsgSeq       int32  `gorm:"column:MsgSeq" json:"MsgSeq"`
	Wxid         string `gorm:"column:Wxid" json:"Wxid"`
	Appid        string `gorm:"column:Appid" json:"Appid"`
	TypeName     string `gorm:"column:TypeName" json:"TypeName"`
}

// TableName Msg's table name
func (*Msg) TableName() string {
	return TableNameMsg
}
