// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMsg = "msg"

// Msg mapped from table <msg>
type Msg struct {
	ID           int32     `gorm:"column:id;primaryKey" json:"id"`
	MessageID    string    `gorm:"column:message_id;not null" json:"message_id"`
	CallbackURL  string    `gorm:"column:callback_url;not null" json:"callback_url"`
	Status       string    `gorm:"column:status;not null;default:'pending'" json:"status"`
	Payload      string    `gorm:"column:payload" json:"payload"`
	CreatedAt    time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	RetryCount   int32     `gorm:"column:retry_count" json:"retry_count"`
	ErrorMessage string    `gorm:"column:error_message" json:"error_message"`
}

// TableName Msg's table name
func (*Msg) TableName() string {
	return TableNameMsg
}
