// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMsg = "msg"

// Msg mapped from table <msg>
type Msg struct {
	ID           int32  `gorm:"column:id;primaryKey" json:"id"`
	MsgID        int32  `gorm:"column:msg_id" json:"msg_id"`
	FromUserName string `gorm:"column:from_user_name" json:"from_user_name"`
	ToUserName   string `gorm:"column:to_user_name" json:"to_user_name"`
	MsgType      int32  `gorm:"column:msg_type" json:"msg_type"`
	Content      string `gorm:"column:content" json:"content"`
	Status       int32  `gorm:"column:status" json:"status"`
	ImgStatus    int32  `gorm:"column:img_status" json:"img_status"`
	ImgBufILen   int32  `gorm:"column:img_buf_i_len" json:"img_buf_i_len"`
	CreateTime   int32  `gorm:"column:create_time" json:"create_time"`
	MsgSource    string `gorm:"column:msg_source" json:"msg_source"`
	PushContent  string `gorm:"column:push_content" json:"push_content"`
	NewMsgID     int32  `gorm:"column:new_msg_id" json:"new_msg_id"`
	MsgSeq       int32  `gorm:"column:msg_seq" json:"msg_seq"`
	Wxid         string `gorm:"column:wxid" json:"wxid"`
	Appid        string `gorm:"column:appid" json:"appid"`
	TypeName     string `gorm:"column:type_name" json:"type_name"`
}

// TableName Msg's table name
func (*Msg) TableName() string {
	return TableNameMsg
}
